name: Test Artifact

on:
  workflow_call:
    inputs:
      distro-slug:
        required: true
        type: string
        description: The OS slug to run tests against
      nox-session:
        required: true
        type: string
        description: The nox session to run


env:
  NOX_VERSION: "2022.8.7"
  COLUMNS: 160

jobs:

  dependencies:
    name: Setup Test Dependencies
    runs-on:
      - self-hosted
      - linux
      - arm64
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Environment
        run: |
          env

      - name: Sleep It Off
        run: |
          sleep 5

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-slug }}-deps

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error

  test:
    name: Test
    runs-on:
      - self-hosted
      - linux
      - bastion
    timeout-minutes: 600  # 10 Hours
    needs:
      - dependencies
    strategy:
      fail-fast: false
      matrix:
        tests-chunk:
          - functional

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python Tools Scripts
        run: |
          python3 -m pip install -r requirements/tools.txt

      - name: Test Python Tools Scripts
        run: |
          python3 -c 'import tools'

      - name: Test Python Tools VM Scripts
        run: |
          tools vm --help
          tools vm create --help

      - name: Start VM
        run: |
          tools --debug --timestamps vm create --destroy-on-failure ${{ inputs.distro-slug }}

      - name: Upload Checkout To VM
        run: |
          tools --timestamps vm rsync ${{ inputs.distro-slug }}

      - name: Destroy VM
        if: always()
        run: |
          tools --timestamps vm destroy ${{ inputs.distro-slug }}

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-slug }}-deps

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
