name: Test Artifact

on:
  workflow_call:
    inputs:
      distro-slug:
        required: true
        type: string
        description: The OS slug to run tests against
      nox-session:
        required: true
        type: string
        description: The nox session to run
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files


env:
  NOX_VERSION: "2022.8.7"
  COLUMNS: 160

jobs:

  dependencies:
    name: Setup Test Dependencies
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Environment
        run: |
          env

      - name: Sleep It Off
        run: |
          sleep 60

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-slug }}-deps

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error

  test:
    name: Test
    runs-on:
      - self-hosted
      - linux
      - arm64
    timeout-minutes: 600  # 10 Hours
    needs:
      - dependencies
    strategy:
      fail-fast: false
      matrix:
        tests-chunk:
          - unit
          - functional

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Environment
        run: |
          env

      - name: Sleep It Off
        run: |
          sleep 60

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-slug }}-deps

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
